version: "3.7"

services:
  server:
    labels:
      - "traefik.backend=${TRAEFIK_BACKEND}"
      - "traefik.docker.network=prod"
      - "traefik.frontend.rule=Host:${TRAEFIK_URL}"
      - "traefik.enable=true"
    networks:
      - default
      - prod
    environment:
      - "DB_HOST=mysql://${DB_USER}:${DB_PASSWORD}@db/${DB_NAME}"
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      - default

networks:
  prod:
    external: true
    name: ${TRAEFIK_NETWORK}
